# Generated by Django 5.1.6 on 2025-02-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='description',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='record',
            name='title',
        ),
    ]
