# Generated by Django 5.1.6 on 2025-02-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_description_record_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='comments',
            new_name='comment',
        ),
    ]
